#!/bin/bash

for i in `git ls-staged`;
do
    php -l "${i}" 2>&1 > /dev/null
    if [[ $? -ne 0 ]]
    then
        echo "WARN: ${i} has a syntax error.";
        exit 1
    fi
done

# Check for merge markers
git_merge_markers.php
