#!/bin/bash

REPO="$1"
TO="$2"
CID="$3"

WAS=`pwd`
CACHE=`echo $REPO | md5sum | cut -d' ' -f1`
_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "$GIT_COW" ]; then
    export GIT_COW="$HOME/.git-cow"
fi

mkdir -p $GIT_COW

CREPO="$GIT_COW/$CACHE.git"

if [ -d "$CREPO" ]; then
    cd "$CREPO"
    git fetch
    cd "$WAS"
else
    git clone --mirror "$1" "$CREPO"
fi

git clone "$REPO" --reference "$CREPO" "$TO"

if [ -n "$CID" ]; then
    cd "$TO"
    git checkout "$CID"
    cd "$WAS"
fi
