#!/usr/bin/python

import subprocess, backwards, os, sys

was = os.getcwd()

_dir = os.path.dirname(sys.argv[0])

gitsub = backwards.check_output(['%s/git-submodule-describe' % _dir])
for line in gitsub.split("\n"):
    if line:
        args = line.split()
        args.insert(0, '%s/git-cclone' % _dir)
        subprocess.call(args)

        os.chdir(args[2])
        subprocess.call(['%s/git-submodule-cclone' % _dir])
        os.chdir(was)

