#!/usr/bin/python

import subprocess, backwards, os, sys

_was = os.getcwd()

_dir = os.path.abspath(os.path.dirname(__file__))
gitsub = backwards.check_output(['%s/git-submodule-describe' % _dir])
for line in gitsub.split("\n"):
    if line:
        args = line.split("\t")
        args.insert(0, '%s/git-cclone' % _dir)
        subprocess.call(args)

        os.chdir(args[2])
        subprocess.call(['%s/git-submodule-cclone' % _dir])
        os.chdir(_was)

